### ISSUE TITLE
Alliance ranks

### ISSUE THREAD

**Issue by J0k3r613** [ronancpl/MapleSolaxiaV2#10]
After creating alliance, Everyone in the Alliance is a member.
-No Master or JrMaster

![unknown](https://user-images.githubusercontent.com/29559705/27313353-7ba0fcfe-553b-11e7-8610-dddc27fd95a7.png)

**Comment by ronancpl** [comment]
Thanks for the feedback! I am checking this out.

**Comment by ronancpl** [comment]
Issue patched.
