### ISSUE TITLE
How to make buy hp npc for meso?

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#100]
How to make buy hp npc for mesos. Link script ty

**Comment by brandy** [comment]
Here's an AWESOME guide on getting started learning scripting for npcs: http://forum.ragezone.com/f428/add-learning-npcs-start-finish-643364/

I doubt anyone will script it for you. All you need to do is add options for which hp pot you wanna buy, then take away mesos from players and give them the hp pot.

**Comment by ronancpl** [comment]
If you wish to have a shop-type NPC:

1) Have an npcid in mind.
2) Add in your db table `shops` (`shopid`, `npcid`) an entry for that npcid.
3) Add entries in `shopitems` ( `shopid`, `itemid`, `price`, `position`) regarding all the items you want the npc to have. Positions given to the items are listed in game from descending order, provided you started to list items positions from 100 and incremented by 4 (as usual here).

**Comment by freshmany** [comment]
nonono, you guys got the wrong item- i know how to make a npc that sell potions -
what im asking for is - i want a make a npc that increase your hp adding - +5000 etc
making npc shop is easy -

i want to know how to make a npc that buy hp for mesos and it increase your hp +5000 everytime you buy it

**Comment by brandy** [comment]
Here is the code for the Rogers Apple quest, which the npc takes away your hp so you can use the apple to learn how to use pots.

```
if (qm.c.getPlayer().getHp() >= 50) {
            qm.c.getPlayer().setHp(25);
            qm.c.getPlayer().updateSingleStat(MapleStat.HP, 25);
        }
```

**Comment by freshmany** [comment]
i mean like - i want to buy hp npc =
let say my hp is at 5000
and i want to buy 2000 more hp gain -
so it will be 7000
if u understand?

**Comment by brandy** [comment]
okay so do something like this?

```
var hp = qm.c.getPlayer().getHp()
var newHp = hp + 5000;

qm.c.getPlayer().setHp(newHp);
qm.c.getPlayer().updateSingleStat(MapleStat.HP, newHp);
```
