### ISSUE TITLE
Setting Up Maplestory Build on Linux Server

### ISSUE THREAD

**Issue by BenjixD** [ronancpl/MapleSolaxiaV2#101]
Hey Ronan, not sure how I could get in touch with you so I thought I'd leave a message here.

I'm looking to setup a variation of the MapleSolaxia build on a linux server. 

I've built the Netbeans project locally and tested a working server locally, but when I moved the build to an Amazon EC2 instance, my client connection can't get past the select character screen (into the game).

Note:
- I have a public IP and the required ports 8484, 7575-7578 are opened (tested through telnet)
- Configurations.ini host has been set to the private IP, and localhost.exe connects to the public IP
- My linux build is running on 1.7.0u2 jre, with the JCE unlimited policies attached **but** my local server's java was built on and is running jdk & jre 1.7.0u79 (I think this might be the problem and if so I'm a klutz)
- I do have ANT installed on the linux server, but I don't know how to build the project from there because it raises some config errors (probably similar to the ones you get running NetBeans on the project for the first time), and I have no clue how to fix these through the command line. Thus I've been copying the build sources through SCP locally to my server (perhaps another issue here)

Any general direction or feedback would be really nice,

Thanks!

**Comment by ronancpl** [comment]
To be able to build, all JAR's inside "cores" folder must be properly set up. Once done that, it's guaranteed that no errors shall appear on the IDE regarding the source code, and it will be ready to compile. How to do that through command line or ANT for that matter, I don't have a clue.

**Comment by ronancpl** [comment]
Maybe JRE7 version 2 is the problem there too. Chances are high that some functions I've been using on the sources/scripts were made available on higher java sub-versions.

**Comment by BenjixD** [comment]
Thanks, I'll get back to you on this. Also, my localhost.exe is being picked up as a trojan after hex-editing the IP. Is there a clean client which won't raise red flags by security software? 

I  think my users and I all find it a little daunting to use.

**Comment by brandy** [comment]
I've yet to find a way to stop anti-viruses picking the client up. I just tell people to set up an exclusion and re-download it.

**Comment by BenjixD** [comment]
Unfortunately I'm still unable to get past the character selection state.

My instance is now running jre 1.7.0u79. My only lead now is that the project must be built in the instance. I'll be looking into how to setup the "cores" through command line. If all else fails I guess I'm moving the a Windows server :/

**Comment by ronancpl** [comment]
@BenjixD I see you changed the name of your DB there. That's probably why you can't pass through the char selection state. Find on the project some reference that still links to the "maplesolaxia" schema name.

**Comment by BenjixD** [comment]
I will double check that. But my local server, which connects to the same DB on my cloud can get me past the character screen.

**Comment by ronancpl** [comment]
So there is some miscommunication between the clients and the server instance you set up, probably a firewall issue... Regarding the detections on the clients, if you search everywhere the clients available will be red-flagged by antiviruses. For as long as I've been using them, I can say there were no colateral effect detected by using them, so I assume they are safe.
