### ISSUE TITLE
Can't recharge stars at any npc

### ISSUE THREAD

**Issue by brandy** [ronancpl/MapleSolaxiaV2#105]
I'm not sure if this is a client issue or a server issue but I'm unable to recharge any kind of stars at any NPC shop. I've tried every kind of star at most shops and none have the recharge option.

I also tried 4 different localhosts and none of them has it either.. Am I missing something?

If anyone has a solution I'd be really happy.

![](https://image.prntscr.com/image/AWXF9j7uThq4b3vlcujnGA.png)

**Comment by tienvtran89** [comment]
Check wz => change all
<double name="unitPrice" value="0,4"/> 
to 
<double name="unitPrice" value="1"/>

It work for me

**Comment by ronancpl** [comment]
That issue is localhost-related. Some localhosts shows that problem, others are functional on this matter.

**Comment by brandy** [comment]
@ronancpl I've tried every single localhost on ragezone, and the clean localhost and none of them show recharge stars O.o

**Comment by tienvtran89** [comment]
Check your wz

**Comment by ronancpl** [comment]
@brandy The MapleSilver ones I've provided definitely has the recharge option. Try those.

**Comment by brandy** [comment]
@ronancpl just tried it again and it doesn't show the option.

I also asked another v83 server to let me use their localhost since they have the "recharge stars" option and upon trying their's it didn't work. I also gave them my wz files and they see the recharge option as well.

I'm also using a clean cloned version of this source. Honestly no idea why myself and nobody who connects to my server can't see the recharge option.

**Comment by tienvtran89** [comment]
Try edit wz find item/consume/0207.img.xml
<double name="unitPrice" value="0,4"/> change all 0,4 to 1

**Comment by tienvtran89** [comment]
Try edit wz find wz/Item.wz/Consume/0207.img.xml
 <double name="unitPrice" value="0,4"/> change all 0,4 to 1

**Comment by brandy** [comment]
@tienvtran89 I'll check that wz and change them and let you know :clown_face:

**Comment by tienvtran89** [comment]
Try 
Wz/Item.wz/Consume/0207.img.xml 
 double name="unitPrice" value="0,4"
Find this change 0,4 = 1

**Comment by ronancpl** [comment]
A clean source, provided it has been setup correctly, running the server on a Windows OS, and may be the client running in compatibility mode for windows XP ~ 7, should be enough to start appearing the recharge option.

**Comment by Soyrce** [comment]
im use Localhost STREDIT, and i cant recharge my stars :(
