### ISSUE TITLE
Pets and bat error?

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#106]
for bat error. how to fix?

[img]https://i.imgur.com/voFqg06.png[/img]

and for this pet - when i do !drop or !item pet id
its already dead and cannot use -
how do make these pets alife?

https://i.imgur.com/U1GUBPG.png

**Comment by ronancpl** [comment]
Bat error: client discovered an exception, there is nothing to be done against it.

Create Pets with command: it is not expected to create pets with commands. If you want so on your server, try fetching for the functions that creates pets when using CS, study it and apply on the "item/drop" command section.
