### ISSUE TITLE
PQ

### ISSUE THREAD

**Issue by J0k3r613** [ronancpl/MapleSolaxiaV2#11]
This error seems to be showing when I try to start a pq.

![capture-001](https://user-images.githubusercontent.com/29559705/27511049-f5b85566-58ea-11e7-988f-1d1e2c48f394.PNG)

**Comment by vcoc** [comment]
are you using java 7? check it

**Comment by ronancpl** [comment]
I vouch for what vcoc said. Nashorn issues normally are related to not using Java 7 when running this server.

**Comment by J0k3r613** [comment]
Is there a way to make it work on jdk 8? (I have not tried uninstall jdk 8 and replacing it with jdk7)

**Comment by ronancpl** [comment]
Nope. This Nashorn framework will only run under jdk 7.
