### ISSUE TITLE
Yellow ? messages

### ISSUE THREAD

**Issue by bbbBacon** [ronancpl/MapleSolaxiaV2#111]
I'm using a clean Localhostv83 and when I type a question mark, a yellow text appears with much of question marks. It's different message for amount of question marks I used (?/??/???).

**Comment by ronancpl** [comment]
Simply inputting "?" will give out these yellow texts? I've tried chatting "?" and it goes normally.

**Comment by bbbBacon** [comment]
It happens most of time, doesn't get triggered all the time. When other people in map types the questions marks we both get the yellow mark, when I type it we both get the yellow message too.

[http://i64.tinypic.com/20pbn8i.jpg](url)

**Comment by ronancpl** [comment]
That's probably a client-side/localhost issue. Hence i'll be closing this.
