### ISSUE TITLE
Roaring Tiger Messenger?

### ISSUE THREAD

**Issue by UltimateMors** [ronancpl/MapleSolaxiaV2#118]
I'm not even sure if this is due to the source or WZ files (What I assumed was the actual cause, because my server was heavily wz editted), but testing it with 3 different types of files, including the ones you provide, and 2 different types of clients over time, they all came with the same results.

For some reason, if you use Roaring Tiger Messenger, it will appear fine, but when going back in, the origins get messed up, and all you see this this:
![2017-10-17_1-43-56](https://user-images.githubusercontent.com/30962403/31648648-ee262cf0-b2dc-11e7-878c-453bb441700e.png)

It will never go away, unless you go the cash shop.

...Also, as a little funny thing, I noticed that "ManagerMsv83.exe" you have in your guide and uploaded to your clientkit was actually one of my old GM servers, ManagerMS v83. I had a v117.2 too. Anyways, thanks for looking into things. 

..Also as another little trick with the vana f1 !fly command, if you use it and then press it while in the middle of changing maps, everything will go black but your character. I found it randomly, but I find it to be cool. Pressing F1 un-dos the effect.
![2017-10-17_1-53-13](https://user-images.githubusercontent.com/30962403/31648860-f6c4014c-b2dd-11e7-8c20-01036276a309.png)

Thanks.

**Comment by ronancpl** [comment]
For this issue the client has messed up. It doesn't erase the image of the used messenger, rather moves it sideways so it doesn't display to the player (only changing images when using another messenger). Therefore, it expects an predefined image length to display. What I could and shall be doing is to crop this item effect to fit in like the others.

**Comment by ronancpl** [comment]
And, oh, that was quite unexpected. So, ManagerMsv83 is not the actual WZ provided by Nexon back then? I've been using it ever since I've took knowledge it was labeled as a "clean v83 setup", something stated up on some corner of the Internet, had no clue it hailed from your server, haha. Well, I intend to keep using it for the purposes of this server setup, so thanks for it!
