### ISSUE TITLE
Mini boss exp glitch

### ISSUE THREAD

**Issue by Enviction** [ronancpl/MapleSolaxiaV2#119]
It seems while in a party people are getting 2.1b exp on mini bosses.

**Comment by ronancpl** [comment]
Would you can on elaborate in what scenario they start getting 2.1b exp? And what would be the mini bosses?

**Comment by Enviction** [comment]
They say when they are in parties together and it might be that or a hs issue. Any mini boss from Faust to Headless Horseman

**Comment by Enviction** [comment]
it actually looks like it's due to people being way lower level than the mob, even if they are 20 levels below they still gain exp.

**Comment by ronancpl** [comment]
This issue has been fixed, thanks for the feedback.
