### ISSUE TITLE
Equip tab is gone after unusual crash

### ISSUE THREAD

**Issue by kukuriri** [ronancpl/MapleSolaxiaV2#122]
So basically, from time to time for some reason, the client crashes and certain people are unable to login(already logged in message). Whenever a GM !dc them or the server is being restarted(even after !saveall) - their equip tab will be gone, and only their equip tab. This has happened multiple times.

**Comment by kukuriri** [comment]
I forgot to mention - no errors nor exceptions are caught when this happens.

**Comment by ronancpl** [comment]
Issue merged with #125.
