### ISSUE TITLE
Custom Feature - Exp cap base on job level

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#123]
i made a custom system where when u reach aka max level of a job it caps the exp so you dont over level if u fail to complete job advs and have to grind more

under maplechar java

replace
private void gainExpInternal
with 
https://pastebin.com/NtMvrn5c
*NOTE delete this line - total = total * ((fame / 10000) + 1); i was using fame to boost exp rates

under game constants add this - may have to add aran as i disabled them on my server for classic reasons lol
https://pastebin.com/ywHCjFey

**Comment by ronancpl** [comment]
It is a nice feature to have. Added it, thanks.
