### ISSUE TITLE
Event start/end + clock

### ISSUE THREAD

**Issue by mrjk611** [ronancpl/MapleSolaxiaV2#127]
Hi Ronan,
I was just wondering how a GM can start an event.
When I teleport to an event map and type !startevent, it says that the event started and upto 50 players may join. I tried joining the event with another character that is not a GM, but I couldn't figure out how to start an event. For example, starting an OX quiz event or maple fitness test event. 

Also, I noticed that the server time is set to GMT-3. I want to change it to GMT-5. How can I achieve this?

**Comment by ronancpl** [comment]
Tbh I never tested the startevent command at all (neither endevent or joinevent for that matter), so if something there is odd you will need to figure it out yourself. By the looks of it, once a player that is on the same channel of the event is moved using the joinevent command, they are already registered in.

To change timezones, lookup the code for keywords like "GMT", that should suffice.
