### ISSUE TITLE
updatePlayerStats vs petStatUpdate

### ISSUE THREAD

**Issue by ExtremeDevilz** [ronancpl/MapleSolaxiaV2#13]
public static byte[] petStatUpdate(MapleCharacter chr) {
                final MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();
                mplew.writeShort(SendOpcode.STAT_CHANGED.getValue());
                int mask = 0;
                mask |= MapleStat.PET.getValue();
                mplew.write(0);
                mplew.writeInt(mask);
                MaplePet[] pets = chr.getPets();
                for (int i = 0; i < 3; i++) {
                        if (pets[i] != null) {
                                mplew.writeInt(pets[i].getUniqueId());
                                mplew.writeInt(0);
                        } else {
                                mplew.writeLong(0);
                        }
                }
                mplew.write(0);
                return mplew.getPacket();
        }

be shifted to updatePlayerStats Example ....

} else if (statupdate.getLeft().getValue() == 0x08) { // Pet
					mplew.writeLong(statupdate.getRight().longValue());
}

+1:  everyone is doing it wrong man.

**Comment by vcoc** [comment]
What you trying to say?

**Comment by ronancpl** [comment]
You're suggesting to add more packet info for updatePlayerStats, right? Is that supposed to make any effect that right now is missing? Other than that I am missing your point, since things seems alright the way I see it... I would be glad if you explain what is happening.

**Comment by ExtremeDevilz** [comment]
you dont need petStatUpdate, you can use updatePlayerStats by adding 0x08 since they do the exact same thing.

**Comment by ronancpl** [comment]
I tried many times your solution here, sadly it throwed error -38 (reached EOF)...
