### ISSUE TITLE
randomizer / equip drop exception

### ISSUE THREAD

**Issue by aiesha-1** [ronancpl/MapleSolaxiaV2#130]
java.lang.IllegalArgumentException: bound must be positive
at java.util.random.nextInt(Unknown Source)
at tools.randomizer.nextInt(Randomizer.java:14)
at server.maps.maplemap.dropFromMonster(MapleMap.java:551)
at [MapleMap dropFromMonster(dropOwner, monster);]
at [MapleMap killMonster(monster, chr, withDrops, 1);]
at [MapleMap damageMonster >if (killed) { killMonster(monster, chr, true);}
at net.server.channel.handlers.abstractdealdamagehandler.applyattack(AbstractDealDamageHandler.java:480)
at net.server.channel.handlers.closerangedamagehandler.handlepacket [ln 189]
and ofc at mapleserverhandler.messagerecv [158]

when i started the beginner quest to kill 10 blue shells and 10 spores for heena or something, i hit my second or third blue snail and it froze in place, still walking animation, attacking it doesnt knock it back or kill it. essentially when this error goes off, a mob had been bricked into a map until restart. i registered an account and typed this by hand.

______'
unrelated, but while im here, preparedStatements never timeout..
shouldnt something like:
if (ps.getQueryTimeout() == 0) {
  
 ps.setQueryTimeout(ServerConstants.QUERY_TIMEOUT);
}
be used? (btw my timeout it set to 300, or 5 mins, if any query takes longer than 5 mins it times out and throws exception, rather than lagging the server?

**Comment by aiesha-1** [comment]
p.s
this happened to me with the revision released a few days ago on the 13th, i didn't edit much besides changing true or false values in some constants.

i hope this helps! i appreciate your time put into this ronan

**Comment by ronancpl** [comment]
Figured out the source of the problem. Shall be normalized next commit.

**Comment by ronancpl** [comment]
About setting timeout for queries, I don't believe they are really necessary. The queries are made to be swift enough to not pass a deadline of 30 seconds.

It should be a problem if PreparedStatements were not being properly closed when finishing their service, but that's not the case. As long as I could see, everything is being closed properly, so this shouldn't be an issue.

Another thing, timing out fetched queries would be a huge throwback on the server logistics, I think. Some functions expect to receive data to do some vital operations over there. Timing out would not be a choice, really.

**Comment by aiesha-1** [comment]
thank you ^^

**Comment by ronancpl** [comment]
No problem.
