### ISSUE TITLE
EXP rate

### ISSUE THREAD

**Issue by mrjk611** [ronancpl/MapleSolaxiaV2#131]
Hey, 

I want to set the player's base exp rate as 22x 
and when the player reaches lvl 150, the exp rate decreases to 20x and every 10 levels after 150, exp decreases by 2x. 

I also want to make the level cap as 250.

I looked at every file that I could find usage of "200" or "level" or "maxlevel".

I changed any lines that says 200 to 250. 
I've also modified the EXPtable file and added more exp that's still under the max number. 

But it just doesn't seem to work and I really need help.

How could I change the level cap?

And how can I set player's exp rate to modify based on their level?

**Comment by ronancpl** [comment]
Firstly you must take note of a few things:
    - The functions to be used whenever a player "changes rates based on their levels" are depicted on the primal/dual functions revertLastPlayerRates() - setPlayerRates(), on MapleCharacter. (As a matter of fact, on my server they only kick in when level mod 20 == 0, you may want to change that.)
    - revertLastPlayerRates(): this removes the rates a player gained based on their level before levelup.
    - setPlayerRates(): applies the rates of the new level.

Revert() must always backtrack the operations from set().

Said that, you will need to tweak those two functions, setting the logic you want to make for your server.

Regarding max level of a player, see the getMaxLevel() function, still on MapleCharacter.

**Comment by mrjk611** [comment]
Hey,

So I read many guides on how to change the max level and I did. When I use a npc to levelup or !level to levelup, I can level beyond 200. However, when I level up to level 200, the exp becomes 0.

In MapleCharacter, I made sure that if (level==200) is changed to ==250 for it to be set.exp(0);

I also modified the EXP table and it should work but as soon as a player gets to level 200, exp just becomes 0. How can I fix this?

**Comment by ronancpl** [comment]
Have you changed things on constants.ExpTable in such a way that the EXP table goes all way from 200~250 (that is, the exp table must now have a total of 250 entries), changed the getExpNeededForLevel() function and changed the getMaxLevel() back on MapleCharacter?

It would be strange enough if even after these changes you can't seem to pass level 200. If that's the case, then the client is the one to blame, as it may be blocking level past 200 locally.

**Comment by mrjk611** [comment]
I've added screenshots to make this easier.

I counted the ExpTable entries and it does have 251 entries. 
getExpNeededForLevel is changed as well as getMaxLevel().

Can you find anything wrong with the code that stops players from gaining exp after lvl 200?

<img width="749" alt="1" src="https://user-images.githubusercontent.com/33470954/33069210-c5765242-ce81-11e7-89e1-9b726a01e3fd.PNG">

<img width="372" alt="2" src="https://user-images.githubusercontent.com/33470954/33069212-c8400b12-ce81-11e7-93b4-13e557c5a914.PNG">

<img width="575" alt="3" src="https://user-images.githubusercontent.com/33470954/33069216-c9d00cac-ce81-11e7-9464-5dd2a35d2db8.PNG">

<img width="485" alt="4" src="https://user-images.githubusercontent.com/33470954/33069225-ce24b0b4-ce81-11e7-9a6b-3f97e3642623.PNG">

<img width="691" alt="5" src="https://user-images.githubusercontent.com/33470954/33069227-cffbeb1e-ce81-11e7-8706-be1baadd32b0.PNG">

**Comment by ronancpl** [comment]
This way, it should level up past 200 normally. If that is not happening, that's because the client is hardcoded to cap the player's max level at 200, nothing can be done on the server source to remove that cap, only client editing will solve.

**Comment by mrjk611** [comment]
Do you know how to edit the level cap on client?

**Comment by ronancpl** [comment]
Nope.

**Comment by ronancpl** [comment]
Closing this since turned out to be client-side issue.
