### ISSUE TITLE
Is Aran working?

### ISSUE THREAD

**Issue by marcuswoon** [ronancpl/MapleSolaxiaV2#135]
Hi,

i have tested this over the weekends, Is Aran working? I cant seems to get past the first quest (second map).
Just want to check if this is the problem on my side or Aran is not working in this version.
The log shows scripts not found?

ADDED info: this quest doesnt seem to work on my end. http://maplestory.wikia.com/wiki/Quests/6/Find_the_Missing_Kid_1

Thank you.
Marcus

**Comment by ronancpl** [comment]
That quest, and Aran as well, works out just fine. Can't guarantee that if you are not using the wz/wz.xml pair I've provided.
