### ISSUE TITLE
Hi Friend

### ISSUE THREAD

**Issue by NovaStory** [ronancpl/MapleSolaxiaV2#14]
How about, I can help you in some simple things clear if you can?
Like, what's up in Ragezone to add as a console?

**Comment by vcoc** [comment]
Any help is always welcome, just remember to send the pull request with the description of your fix or idea. XD

**Comment by ronancpl** [comment]
As vcoc said, any help is welcome. Just make it clear what you would like to change on your pull requests to make it easier to understand your point.

**Comment by NovaStory** [comment]
Thanks very much :D
