### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by oScreaming** [ronancpl/MapleSolaxiaV2#15]
Hello, Do you have a discord? If so whats your name and #. Great job on the updates!

PS: Your Boss Rush PQ doesn't read party leader correctly it just says "make sure your party leader talked with me"

EDIT: Your new horntail thing is broken as well. Not sure if its your isLeader method but it is broke.

**Comment by Ixeb** [comment]
Yep, the isEventLeader function seems to be broken for me aswell :)

**Comment by ronancpl** [comment]
Hi. I've got aware of this isEventLeader problem, this will be patched soon. Regarding the HT, everything seems fine for me. Did you meet any of the needed requirements before talking with Keroben, the gatekeeper?

My discord is #4421 ronancpl, feel free to contact me there.
