### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by aliceric27** [ronancpl/MapleSolaxiaV2#17]
it's the script problem?
[logs.zip](https://github.com/ronancpl/MapleSolaxiaV2/files/1170506/logs.zip)

**Comment by ronancpl** [comment]
This is a issue with the Nashorn script engine, it is reported to not work well on Java 8 VM. Get the Java 7 version to run this server.

**Comment by aliceric27** [comment]
that's right ! I was installed jre6.7.8 and uninstall jre8 it's working prefect now thanks
