### ISSUE TITLE
4th job Bishop Gene dcs whole map

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#20]
genesis skill dcs everyone on map.

**Comment by freshmany** [comment]
Please help with the bishop skill. Its like one of the important skill ingame. Ty

**Comment by resinate** [comment]
its other skills also

**Comment by freshmany** [comment]
What other skill? If it hit 15 monster they dc? Oo

**Comment by resinate** [comment]
all 6 of mage spells, adv and koc

**Comment by ronancpl** [comment]
I'll see what I can do. If they require intense packet fixings, there's not much I can do.

**Comment by resinate** [comment]
dont mess with this and close this asap lol im making a new issue reguarding this issue
