### ISSUE TITLE
importpackage on map scripts

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#26]
any chance of adding this in down the road?

**Comment by ronancpl** [comment]
Add what? importpackage can be used whenever one wants on a script.

**Comment by resinate** [comment]
its in all ur map scripts lol

**Comment by ronancpl** [comment]
Some of these importPackage(Packages.server.life) may have been declared but unused, indeed. That's what somebody else did, nothing that relevant btw. Thanks for pointing out, though.
