### ISSUE TITLE
Alguns comandos quebrados e etc...

### ISSUE THREAD

**Issue by vcoc** [ronancpl/MapleSolaxiaV2#3]
Eae ronan, venho acompanhando o seu trabalho desde inicio de 2016 e quando você deu uma pausa no server, eu baixei ele e tinha corrigido, adicionado e removido muitos comandos do maplesolaxia mas eu tive problema com o meu pc e precisei formatar e acabei perdendo tudo, enfim, dê uma olhada nos comandos, tem uns que são inúteis e outros que não funcionam corretamente, ex: comando de UNBAN, dê uma olhada nesse comando pois ele não está retirando o "1" da tabela de ban na database; Boa sorte com o seu desenvolvimento, estou sempre de olho ;)

**Comment by ronancpl** [comment]
Pois é, em 2016 mesmo eu tinha dado uma pausa por estar na reta final da faculdade, recentemente voltei à ativa. Como vc pode perceber nos últimos commits, estive me atendo mais na resolução de bugs que aparecem na visão do usuário do jogo (mob não dropando item, reator que deveria desempenhar alguma ação mas está falhando, erros em PQs/eventos, etc etc).
Ainda não parei para verificar que comando (de GM ou não) está quebrando ou não, como esse que vc mencionou, mas vou verificar assim que der.
Bacana vc estar acompanhando meu projeto, fico feliz de saber que o meu trabalho está ajudando alguém. Obrigado pelo feedback!

**Comment by ronancpl** [comment]
Comando de ban/unban está corrigido agora.
