### ISSUE TITLE
No damage to monsters when stunned

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#32]
https://gyazo.com/a7824d4402067e17405678db602b7b87
gif animation of the bug

thats what my buddy see's he says its from archers only
i noticed once that one snail got stunned he couldnt kill anything after that

no mods were done in src to trigger this

**Comment by ronancpl** [comment]
Firstly, why in the world is this snail dropping Perfect Pitch? (not to mention why other items have not been dropped as well, although can be relatable on a 1x drop scenario). I believe either your DB is somewhat corrupted, or your server as a whole is not entirely clean as you claim it is.
Mobs not being killed/stunned after damage dealt is a high symptom of a server crash, and those are simply not happening here. Reinstall your server, use the provided WZ files and, in case of that happening again, show me all the process you take to reach this scenario.

**Comment by resinate** [comment]
im using perferct as a resource drop, so i added it to global drops not hard to do lol. u forget about the global drop table lol?
