### ISSUE TITLE
[EllinPQ] Stone Centipedes

### ISSUE THREAD

**Issue by Ixeb** [ronancpl/MapleSolaxiaV2#33]
The stone centipedes do not drop any items. They are supposed to drop a "Diluted" item when killed near a pool of water and drop a "Concentrated" item when killed elsewhere.

http://bbb.hidden-street.net/party-quest/ellin-forest/stage-2

**Comment by ronancpl** [comment]
It is mandatory to load db_drops.sql after db_database.sql. Did you load this on your server?

**Comment by Ixeb** [comment]
Yes, I did

**Comment by ronancpl** [comment]
Well, as of the current (rev101) db_drop.db, line 18817, the rock centipede mob from the PQ is indeed dropping the concentrated item. In-game, too, I can see it being dropped. I am using the provided WZ here.

**Comment by ronancpl** [comment]
Btw, the mob will only drop the concentrated version. The fountain in the middle will "consume" this and drop the pickable version.

**Comment by Ixeb** [comment]
Ah I see, okay thankyou very much :)

**Comment by Ixeb** [comment]
The reactor in ellinPQ that eats the concentrated poison and spits out the diluted poison only seems to work once?

**Comment by ronancpl** [comment]
Nope, they should work more than once. Methinks the custom Wz is needed to take effect. I had to mod this reactor's structure.

**Comment by Ixeb** [comment]
Ah ok thanks :)
