### ISSUE TITLE
painus breaks server wide re-spawn

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#36]
ppl enter painus and when they do entire spawn timer breaks for some reason. no mods where done.

**Comment by freshmany** [comment]
I love this source hardout.. just need help with these mini bug. Very goood source. I hope they can help us fix these mini bugs asap =)

**Comment by ronancpl** [comment]
Back ago, there was that issue where Pianus was spawning his spawns out of place in the map (I'm assuming you're talking about the Pianus normal location in Aqua Road). The server would log the NullPointerException on the cmd. If you got it there, could you paste the error log? Here it seems fixed already.

**Comment by resinate** [comment]
yea no errors just freezes all timers in server dont know whats up

**Comment by ronancpl** [comment]
Nope, didn't tracked that. I've been making many changes all around the WZs, many contents already modified to better improve the gameplay, almost hard to stick with the clean WZs now on this server.

If one still wants to get a shot on the changes, the best option would be open up HaRepacker, dump up all the img.xml from the original v83 and mine's and match file to file using a file differ program like WinMerge. Rather impractical, though.

**Comment by resinate** [comment]
im using clean wz files and got everything working fine had to change pianus into an area script boss but thats all i had to do

**Comment by ronancpl** [comment]
Whoa, that's nice the scripts worked fine. The guys at Solaxia already had some implemented, I just added more on those areas with lacking bosses.
