### ISSUE TITLE
possible work on dojo scripts?

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#38]
everything seems fine on dojo but this line is missing 
ms.getPlayer().setDojoStart();

seems that everything else is there lol

**Comment by ronancpl** [comment]
Sadly, the guys at Wz swapped dojang_1st with dojang_eff, when they were referencing script names in their files. Result: I've changed back the way it should be on my Wz's. Next commit, if one plans to stick with the clean Wz's, will need to swap name of scripts on the map scripts "dojang_Eff" <-> "dojang_1st" to make it work properly on their servers.

Dojo's here seems to work fine now.
