### ISSUE TITLE
[FIX] java 8 map script issue

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#39]
replace
            fr = new FileReader(scriptFile);
with
            fr = new FileReader(scriptFile);
            portal.eval("load('nashorn:mozilla_compat.js');");

i dont use gith enough to make pull fix things so this is to help u ronan

reason i posted this is for use custom modders, we can have unlimited access to any part of the src from map scripts without having to make useless addons lol

**Comment by ronancpl** [comment]
"unlimited access to any part of the src". Wouldn't already have unlimited access on the java src with importPackages?

**Comment by ronancpl** [comment]
portal.eval("load('nashorn:mozilla_compat.js');");

"load" is not defined on RhinoScriptEngine, ScriptException thrown.

**Comment by resinate** [comment]
dunno it worked for me with no issues but im also using java 8
