### ISSUE TITLE
[FIX] Portal bug fixed

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#40]
instead of using random spawn point for normal jumping we do this instead
this is built where if theres no portals on a map, itll revert to random spawn portal.
this fixes issues with mystic doors and FM market where u spawn at the main portal instead of a random portal lol

    public void changeMap(int map) {
        MapleMap warpMap;
        if (getEventInstance() != null) {
            warpMap = getEventInstance().getMapInstance(map);
        } else {
            warpMap = client.getChannelServer().getMapFactory().getMap(map);
        }
        if (warpMap.getPortals() == null) {
            changeMap(warpMap, warpMap.getRandomPlayerSpawnpoint());
        } else {
            changeMap(warpMap, warpMap.getPortal(0));
        }
    }

**Comment by ronancpl** [comment]
Indeed, player would jump to portals when changing maps this way. Implemented a patch to solve this here, will come out soon.
