### ISSUE TITLE
error with rush party quest

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#41]
i traced error back to List<MaplePartyCharacter> getEligibleParty

**Comment by ronancpl** [comment]
I have always been using the getEligibleParty feature, BRPQ included, all way fine to me. What kind of error is that?

**Comment by resinate** [comment]
are u running ur src in java 7 or 8.

**Comment by ronancpl** [comment]
I'm running this in Java7, clearly. Just recently I've been known this thing of not providing downloads for J7 anymore. All I have is that Java 7 installer available on Drive (windows 64bits).

**Comment by resinate** [comment]
yea when i down graded from java 8 to 7 everything seemed to work
