### ISSUE TITLE
2nd job map breaks spawns

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#42]
dunno whats up but going into 2nd job map, one where u get the marbles, breaks server wide respawn timers

**Comment by ronancpl** [comment]
For what job? Have tested plenty already, seemed fine.

**Comment by resinate** [comment]
all the 2nd job maps, when u enter them server bugs out dunno how or why spent 8  hours looking

**Comment by ronancpl** [comment]
There's no problem with the loading/exiting 2nd job map. I've tested here, with 2nd player in HG map spawning normally.

**Comment by resinate** [comment]
yea it was a java 8 bug, java 7 doesnt have this bug
