### ISSUE TITLE
crane in MU lung to orbis broken

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#45]
the cranes doesnt teleport players to orbis

this code needs to be added to npc ID: 2090005
} else if(status == 2) { //under
			if(slct == 1) {
                if(cm.getMeso() < cost[1]) {
                    cm.sendNext("Are you sure you have enough mesos?");
                    cm.dispose();
                } else {
                    cm.gainMeso(-cost[1]);
                    cm.warp(200000100);
                    cm.dispose();
                }
            }

**Comment by vcoc** [comment]
Already have fixed this, thanks for all.

**Comment by ronancpl** [comment]
Issue patched.
