### ISSUE TITLE
possible release/fix for hp system

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#46]
https://cdn.discordapp.com/attachments/316844071224213504/345803609486655488/unknown.png

if u wanna sit and talk and i can explain how to install this system. it works 100% for me weve been using it for few weeks now

**Comment by ronancpl** [comment]
What exactly should be wrong with the hp system? Seems to work fine already.

**Comment by resinate** [comment]
system i made allows HP far higher than 2bil, cool custom server feature for ppl to use

**Comment by ronancpl** [comment]
I'll stick with the vanilla 30k maxHP for this server. Thanks.
