### ISSUE TITLE
maplemapfactory reactor fix

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#47]
in ur newest reactor update u need to put it like this for it to work else server errors like no other

        myReactor.setName(MapleDataTool.getString(reactor.getChildByPath("name"), ""));
        myReactor.resetReactorActions();

**Comment by ronancpl** [comment]
Idk why setName should be postponed like this, they read things just the same way. Well, if they gave out errors some way i'll just put that way. Will be there at the next commit.

**Comment by resinate** [comment]
do not do this lol do not do this that was a line i missed when updating your way works fine
