### ISSUE TITLE
tot quest chain broken

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#49]
some of quests in tot cant be completed.... ppl keep whining about it to me lol on my server

**Comment by ronancpl** [comment]
Never truly tested it before, hoped that was working already. Very well, i'll talke a glance on it at the due time.

**Comment by resinate** [comment]
its quest where u have to talk to you 1st job instructor is where it broke for us

**Comment by ronancpl** [comment]
Fixed. However provided wz is needed for them to take effect.
