### ISSUE TITLE
Fechado

### ISSUE THREAD

**Issue by vcoc** [ronancpl/MapleSolaxiaV2#5]
Fechado

**Comment by ronancpl** [comment]
Tentei corrigir o problema dos itens de alimentação dos pets. Agora me parece ok, por favor responda se eu estiver enganado.
Tentei verificar sobre mudar o nome dos pets, não encontrei erro algum... Que tipo de caso que vc usou pra chegar nesse erro?
De novo, obrigado pelos feedbacks, me auxiliam bastante!

**Comment by vcoc** [comment]
Quando eu usava o item de alterar o nome dos pets, ele não atualizava o nome, ele alterava na database e etc, mas no jogo não atualizava, eu tinha que trocar o canal etc e na cmd aparecia o erro.
Error for player ; OTemido on map ; 2000000 - account ; adminAll: 4F 00 0A 00 50 E3 4E 00 07 00 42 61 72 62 61 72 61 4E 80 58 00Now: 4E 80 58 00java.lang.NullPointerException	at client.inventory.ModifyInventory.<init>(ModifyInventory.java:17)	at client.MapleCharacter.forceUpdateItem(MapleCharacter.java:1603)	at net.server.channel.handlers.UseCashItemHandler.handlePacket(UseCashItemHandler.java:383)	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:136)	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)	at java.lang.Thread.run(Unknown Source)

**Comment by vcoc** [comment]
Quando eu estava jogando de aram e entrei no CS eu tive este erro aqui tbm.
---------------------------------------------------------------------------------------
java.lang.NullPointerException
at client.MapleCharacter.cancelBuffEffects(MapleCharacter.java:725)
at net.server.channel.handlers.EnterCashShopHandler.handlePacket(EnterCa
shShopHandler.java:46)
at net.MapleServerHandler.messageReceived(MapleServerHandler.java:136)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.mess
ageReceived(DefaultIoFilterChain.java:690)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessage
Received(DefaultIoFilterChain.java:417)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(Def
aultIoFilterChain.java:47)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.mes
sageReceived(DefaultIoFilterChain.java:765)
at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutpu
tImpl.flush(ProtocolCodecFilter.java:407)
at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(Prot
ocolCodecFilter.java:236)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessage
Received(DefaultIoFilterChain.java:417)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(Def
aultIoFilterChain.java:47)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.mes
sageReceived(DefaultIoFilterChain.java:765)
at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFi
lterAdapter.java:109)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessage
Received(DefaultIoFilterChain.java:417)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageRece
ived(DefaultIoFilterChain.java:410)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(Abstract
PollingIoProcessor.java:710)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(Abstr
actPollingIoProcessor.java:664)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(Abstr
actPollingIoProcessor.java:653)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(Ab
stractPollingIoProcessor.java:67)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run
(AbstractPollingIoProcessor.java:1124)
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnabl
e.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
at client.MapleCharacter.cancelBuffEffects(MapleCharacter.java:725)
at net.server.channel.handlers.EnterCashShopHandler.handlePacket(EnterCa
shShopHandler.java:46)
at net.MapleServerHandler.messageReceived(MapleServerHandler.java:136)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.mess
ageReceived(DefaultIoFilterChain.java:690)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessage
Received(DefaultIoFilterChain.java:417)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(Def
aultIoFilterChain.java:47)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.mes
sageReceived(DefaultIoFilterChain.java:765)
at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutpu
tImpl.flush(ProtocolCodecFilter.java:407)
at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(Prot
ocolCodecFilter.java:236)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessage
Received(DefaultIoFilterChain.java:417)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(Def
aultIoFilterChain.java:47)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.mes
sageReceived(DefaultIoFilterChain.java:765)
at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFi
lterAdapter.java:109)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessage
Received(DefaultIoFilterChain.java:417)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageRece
ived(DefaultIoFilterChain.java:410)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(Abstract
PollingIoProcessor.java:710)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(Abstr
actPollingIoProcessor.java:664)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(Abstr
actPollingIoProcessor.java:653)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(Ab
stractPollingIoProcessor.java:67)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run
(AbstractPollingIoProcessor.java:1124)
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnabl
e.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by vcoc** [comment]
O comando do !horntail não funciona corretamente, tenta substituir por outro comando que faça aparecer o boss diretamente, sem as animações. Tenta pegar de uma source v62.

**Comment by vcoc** [comment]
Vou procurar outros bugs e vou te avisando. Não sei se você ja viu, mas esses são os bugs que ja veio com o MapleSolaxia.

- While exiting the cash shop, you don't get added back to the channel server correctly causing issues with killing monsters, changing maps, etc. Changing Channels will add you back correctly.
- Mystic Door needs a lot of work to be functioning correctly. Found some of the additional packets relating to joining parties, etc.
- The TimerManager will hit a task that locks the thread where it can't continue, causing anything using timers to stop working after all the threads get locked. We were in the process of debugging this when we went down.

**Comment by ronancpl** [comment]
Ok. No momento estou reescrevendo os códigos das PQs mais gerais (KPQ, LPQ), que atualmente estão uma bagunça e algumas não funcionam como deveriam. Vou estar checando e corrigindo esses bugs do Solaxia com o tempo. Desses daí já corrigi a saída do CS, já parece estar normal.

**Comment by vcoc** [comment]
OK :) Uma dica, cria um arquivo de texto na pasta do servidor e coloca as coisas que estão funcionando, ai você já tem uma noção do que funciona e o que ainda falta. Tamo junto!

**Comment by vcoc** [comment]
PyramidPQ não funciona. Caso você clique no npc da PyramidPQ, a sua conta fica bugada e precisará criar outra.

**Comment by vcoc** [comment]
Netts Pyramid não funciona. Caso você clique no npc da PyramidPQ, a sua conta fica bugada e precisará criar outra.

**Comment by vcoc** [comment]
IDEIA: Ronan, tava vagando pelo github e achei esse desenvolvimento e fui olhar os arquivos dele e achei interessante os "comandos" para que os pet de gm não sintam fome, entre outros tbm, dê uma olhada nisso https://github.com/nostalms/MapleStory/blob/master/src/constants/ServerConstants.java

**Comment by ronancpl** [comment]
É, cara. A mecânica dessa PyramidPQ parece bem chatinha, envolve abordagem de pontos feitos nessa PQ, uma barrinha de ACT que não parei pra entender direito o objetivo dela, entre outras coisas. Parecido até com o Monster Carnival tb, que tem suas próprias mecânicas e sistema de pontos. Em resumo, uma PQ não tão convencional assim... Díficil eu achar animo pra tentar resolver essa aí, por ora. Basicamente, o que eu fiz foi desativar esse NPC daí pra não ocorrer mais dessas coisas de bloquear conta.
