### ISSUE TITLE
NPC issues

### ISSUE THREAD

**Issue by Ixeb** [ronancpl/MapleSolaxiaV2#51]
For some of the NPC's (Steward Command NPC and LudiPQ Blue Balloon) I get errors such as;

"Cannot call method "split" of null " - Blue Balloon in LudiPQ

**Comment by ronancpl** [comment]
These functions should already be present on a Java 7 developing environment. Are you using J7?

**Comment by Ixeb** [comment]
Yes I am using JDK 7

**Comment by ronancpl** [comment]
LudiPQ npc scripts should work fine if you started a PQ normally, else things will start to throw rampantly. Regarding Steward, right now it is working here, although I may have made some fixes since last commit, idk. Should work properly soon.

**Comment by resinate** [comment]
theres a nasty portal bug going on, i had to revert it cuz it was randomly dc ppl and causing extremely slow map loads
