### ISSUE TITLE
using gain item exp dcs map

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#52]
using item gain exp, even inside an NPC if u gain too much exp even targeted on a single char, itll overload all other clients in the map and dc them. not you tho. i think its from packet overflow issue.

it seems changing the method to this works

    public void forceUpdateItem(Item item) {
        final List<ModifyInventory> mods = new LinkedList<>();
        mods.add(new ModifyInventory(3, item));
        mods.add(new ModifyInventory(0, item));
        this.client.announce(MaplePacketCreator.modifyInventory(true, mods));
    }
this.client.announce(MaplePacketCreator.modifyInventory(true, mods)); was changed added this.

**Comment by ExtremeDevilz** [comment]
dude submit a pull request.

**Comment by ronancpl** [comment]
Ehhh... That "this." before the client.announce() represents essentially the same thing, the property "client" of the very object you are manipulating is being called. Are you sure you got an improvement from this? I can add this anytime, but to me it achieved nothing.

**Comment by resinate** [comment]
NOOOOO im saying the dc is in this code LOL this is NOT a fix
