### ISSUE TITLE
Guild Issue 

### ISSUE THREAD

**Issue by Ixeb** [ronancpl/MapleSolaxiaV2#53]
The players on my server have run in to a guild issue where, if a regular player joins a guild, sometimes their displayed level in the guild isn't the same as their actual current level. It seems to display the level that the character was when the server first opened (if they levelled up after the server opened and before they joined the guild).

If the player joined the guild before levelling up, the correct level seems to be displayed and the levelup messages are also displayed. No idea what could be causing this... x_x

**Comment by ronancpl** [comment]
There were indeed some inconsistencies with MapleCharacter and MaplePartyCharacter within the code. Expected to display again normal information after leveling up/changing job once joined in a guild. Issue solved here.
