### ISSUE TITLE
found dc issue with this packet

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#54]
MaplePacketCreator.modifyInventory(true, mods)

when its ran more than 16 times at once it dcs everyone on map but person gaining the exp/levels on items

**Comment by ronancpl** [comment]
Setup a scenario for me on how I should try this issue here to test.

**Comment by resinate** [comment]
heres whats going on, its like a quad array running

Array(all players Array (all equipped items Array (gain exp Array(apply each stat on equip))))

this over flowing happens when u kill say 10 targets at once with FMA

for me i managed to push update on items from each level up to all levels up then update, but still causes a packet overflow. this also happens if u have too many 100% drop rate items using FMA. i dunno how to uncap amount of packets being sent all at once.

**Comment by resinate** [comment]
soo i replaced ur forced item update with this

    public void forceUpdateItem(Item item) {
        forceReAddItem_NoUpdate(item, MapleInventoryType.EQUIP);
        client.getSession().write(MaplePacketCreator.modifyInventory(false, Collections.singletonList(new ModifyInventory(0, item))));
    }

and it worked perfect. im actually able to gain unlimited exp now. found and modded code from another source
