### ISSUE TITLE
black taxi causing server locks?

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#59]
when using black in leafre its causing respawn timers to break - no map respawns

npc id - 2023000

**Comment by ronancpl** [comment]
Seems fine here.

**Comment by resinate** [comment]
ull know it happens when u get slow map transition may take few tries, it diff happens 100% if u come off a boat or an event like bossrush. ull know when u trigger the error when it takes like 5-10 seconds to appear in map and BGM bugs out

**Comment by ronancpl** [comment]
Already entered BRPQ 5+ times, defeated all bosses until RS1, left from portal (then loop); not got slowed neither BGM problem.

**Comment by resinate** [comment]
ronan is there a way to msg u on steam or disc?

**Comment by ronancpl** [comment]
For now GH will need to be enough. Sent today the machine im used work on to maintenance, with disc and all else there. Wont bother to install disc on this one just for use on few days.
