### ISSUE TITLE
tot still bugged on quests

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#61]
applied all ur updates + wz mods
quest still loops on id 3506-3507 and 5 sub quests
pick up quest at temple keeper, then time keeper, then sends you to job guy then it sends you back to templer keeper. looping same quest over and over

this is why you dont do wz mods to fix quests lol

**Comment by ronancpl** [comment]
Well I did state this instance of server wasn't following the original v83 WZ files. Changes needed, couldn't make it simple, WZ changes are sure to follow here.

**Comment by resinate** [comment]
i used ur wz edits quest chain was looping on keeper quest

**Comment by ronancpl** [comment]
Well, tried again here, set all the system on another machine I have. Everything worked fine, all the way to Pinkbean exped.
