### ISSUE TITLE
special kind of help/issue

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#64]
i need some help from you since u made this system

for (Item item : getInventory(MapleInventoryType.EQUIPPED).list()) {} fetches whole list of equipped items

how can pull 1 random equipped item from this list? ive spent 12 hours trying to figure this out

the only thing i managed to create is this
Collection< Item> items = new ArrayList<>(getInventory(MapleInventoryType.EQUIPPED).list());
but after this everything fetches nulls

**Comment by ronancpl** [comment]
To be made clear, MapleInventoryType MapleInventory any of those core-kind of classes of Maple was NOT made by me, I just studied and adjusted them whenever I found something necessary. Regardless that, one must make sure a MapleCharacter object instance of a valid player in-game is being instanced when dealing with these getInventory calls.

For instance, when checking a to-banish player when a mob called BANISH from his skills:
         if(ServerConstants.USE_SPIKES_AVOID_BANISH) {
            for(Item it: this.getInventory(MapleInventoryType.EQUIPPED).list()) {
                if((it.getFlag() & ItemConstants.SPIKES) == ItemConstants.SPIKES) return;
            }
        }

This function tries reads the EQUIPPED items a player has, lists them (none of them are null, else would have exceptions thrown) and fetches for at least one equip with given flag. On other words, if done correctly,  getInventory(MapleInventoryType.EQUIPPED).list() should never give nulls.

**Comment by resinate** [comment]
yea but ur running for commands, i need to run it to pull a random at will to gain item exp. its not as easy as u make it to be

**Comment by ronancpl** [comment]
Provided you have instanced a MapleCharacter correctly:

    public Item getRandomFromEquipped(Item it) {
        List<Item> list = new ArrayList<>(this.getInventory(MapleInventoryType.EQUIPPED).list());
        if(!list.isEmpty()) {
            Collections.shuffle(list);
            return list.get(0);
            
        } else {
            return null;
        }
    }

**Comment by resinate** [comment]
thanks man

**Comment by ronancpl** [comment]
You can't remove an Item from List<Item> while iterating with this very list. You should create a new list and go passing the non-cash items to the new list as you iterate over "list".
