### ISSUE TITLE
Disappearing NPC's

### ISSUE THREAD

**Issue by Ixeb** [ronancpl/MapleSolaxiaV2#65]
Ever since I have gained more players on my server, certain NPC's seem to be disappearing over time. The most common being:
- Shumi (Kerning City)
- Riel (Florina Beach)
- Head Security Officer (Mushroom Forest Field)

Anyone experiencing the same issue as this? Or is it just me

**Comment by Ixeb** [comment]
Maybe this helps;
When I use the !whereami command, the NPC's are no longer present in the list. The NPC's appear to be completely removed from the map until the server is restarted.

**Comment by freshmany** [comment]
happen to me tooo please help fix thanks =]

**Comment by ronancpl** [comment]
It is still pending identification of the source of that problem. NPC's here are working out fine, none disappearing overtime, although I've been running always top-3 hours sessions.

**Comment by ronancpl** [comment]
There was a patch regarding the fix of this issue. Still pending tests to ensure that the issue has been solved or it still lingers around.
