### ISSUE TITLE
How to increase quest exp rate?

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#67]
How to increase quest exp rate?
hello i want to increase all the quest exp rate at 7x exp how do i do that
because i see nothing in ServerConstants about quest rate?

**Comment by ronancpl** [comment]
Quest rate currently uses the same exp rate as player's exp rate. You would need to fetch the ExpAction entry code (the one that gives quest exp to player) and add a multiplier flag there for your quest exp rate.

**Comment by freshmany** [comment]
ty boss =]

**Comment by tienvtran89** [comment]
Copy from moopledev , they have quest rate.
