### ISSUE TITLE
magic stat increasing watk/range

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#69]
i was doing some testing why is magic stat also increasing weapon range?

**Comment by ronancpl** [comment]
Rofl, that should happen in any scenario.

**Comment by resinate** [comment]
00780620 - MAGIC CAP on client

changing that cap from 1999 to w/e higher increases normal damage as well. so dumb

**Comment by ronancpl** [comment]
Since editing localhost caps goes beyond server development, i'm closing this issue.
