### ISSUE TITLE
Started quests

### ISSUE THREAD

**Issue by cljnilsson** [ronancpl/MapleSolaxiaV2#71]
MapleCharacter victim = cserv.getPlayerStorage().getCharacterByName(sub[1]);
            List<MapleQuestStatus> quests = new ArrayList<MapleQuestStatus>(victim.getStartedQuests());
            
            for(int i = quests.size() - 1; i >= 0; i -= 1) {
                MapleQuestStatus q = quests.get(i);
                player.message("" + q.getQuest().getId());
            }

The following code writes out a bunch of ids of quests that are not "started", in fact I have 4 quests active but get 10 quests listed.

https://i.gyazo.com/1a28553bdaceb72bf39e807273b1d961.png

The Secret of the Golden Feather - 28214
Is a quest I already completed for example.

This leads to quest drops dropping even after the quest is complete.

edit: some of the quests were from Dalair who gives out the quests periodically. Completing those removed 4 of the quests.

edit2: 2 more quests picked up automatically regarding exploring.

However I still got a quest with the id "-31066" which is odd.

**Comment by ronancpl** [comment]
AFAIK Dalair quests are broken, didn't got the time to test them. Since questids uses short data-type, this negative id represents an overflowed questid 34470. Does all quest items become broken, or just these picked quests had item dropping even after completion?

**Comment by cljnilsson** [comment]
Alright, I will just keep an eye out on the commits to see when it is eventually fixed, it is not a big deal anyway.

In my limited tests, it is only these few hand picked ones which I had to add manually.

**Comment by cljnilsson** [comment]
I wiped my SQL database completely and updated it with the recent and updated SQL files which had like 10k more entries.

I started doing the pirate questline for the low level demon hat.
While I was in perion working on the The Mystery of the Red Portion (id 28246) an item called "Piece of White Pants" dropped, a quest item.
I looked it up in the database and it it supposed to drop for quest 28248, which is the followup quest.

So something definitely seems to be wrong with quest item drops.

**Comment by ronancpl** [comment]
To a quest item not appear to the player two conditions must be met: firstly, on reactordrops/drop_data tables questid set to anything else but -1/0 respectively. Secondly, client WZ's and server WZ's must be conformant on flagging an item "quest item" (it is shown when hovering the mouse by the item on inventory on orange-ish color).
As a matter of fact, here the Piece of White Pants only appears if the quest is started, concluding it will no more show the item to the player. Maybe I flagged it as quest item on my WZ, not sure about that now.

**Comment by cljnilsson** [comment]
Well I did download wz files from: https://drive.google.com/drive/folders/0BzDsHSr-0V4MYVJ0TWIxd05hYUk

So it is possible that it might be my local client side WZ that is screwing around? which of the two am I supposed to use? the rev101_wz or client_wz?

**Comment by ronancpl** [comment]
client_wz was the one to refer to the lastest updates. The way it seems to be there, both conditions are meeting, it should indeed be hiding the quest items.

**Comment by cljnilsson** [comment]
Well it does not :-/
I take you you cannot reproduce such errors either? because I just spawned 50 green mushrooms and killed then with killall and got an etc quest item called Living Fossil if I remember correctly.

**Comment by ronancpl** [comment]
Yes, I couldn't reproduce it. Installed this source on another computer and it was hiding things fine. Are you sure you followed all the steps on readme thoroughly?

**Comment by cljnilsson** [comment]
Seeing as the server is up and running I could not really screw up the setup.

I got a few ideas.
Firstly, I am running JDK 1.8 instead of 1.7, I can compile the code with JDK 7 just fine but I saw no difference so I went with 8. It is also noteworthy that I get bombarded with event errors unless I have Java8=true I do not know if that is somehow a possible cause of error. 

Secondly, I use a modified win 10 client instead of a clean localhost. I will test with a clean one shortly since I do not know if the win 10 client has other modifications.

**Comment by cljnilsson** [comment]
Ok so I did a bit of debugging.

I removed my database and made a new one from scratch with the updated DB files. No additions other than making an account.
I then downloaded the files from github, I did not compile them and used them as they came no a single file edited except setting Java8 to true.

I entered the game, used !spawn 8140000 500 and got the quest item Cold Heart of the Wolf and Lycanthrope's Plans both are classified as quest items.

So my conclusion is that the error is not in the source code, nor the database. It has to be the java8=true that somehow screws it over.

**Comment by resinate** [comment]
dont use java 8 at all, just un-install it go with jdk 7 it may display no errors but it does cause errors, PQ in game didnt work anything.

**Comment by cljnilsson** [comment]
OK I FOUND THE BUG!

actually there was nothing wrong at all.
THe problem was that I used !itemvac to loot all the mobs

Itemvac somehow grabs invisible items or something. I spawned 500 lychanropes and did not get a single quest item. There was nothing lying on the ground and then I used !itemvac and I got the quest items.

**Comment by ronancpl** [comment]
Oooh, alright. This does exactly what it should do, vaccuum the map. Didn't even bother to check if a player can pick it up or not, it just does that.
