### ISSUE TITLE
adding long values to mapledatatool

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#73]
heres a small addon from upper level srcs
adds long support to mapledatatool

https://pastebin.com/SuTb0q6c

its a system needed if you wanna use systems like HP > 2b

**Comment by Alex-0000** [comment]
How come you didn't make a pull request? Do you need help with using git?

**Comment by resinate** [comment]
nah i left the scene im not working on maple anymore
