### ISSUE TITLE
converting boss hp bars into % based 

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#74]
this is a must have system for using over 2b HP with boss bars

    public static byte[] showBossHP(int oid, long currHP, long maxHP, byte tagColor, byte tagBgColor) {
        final MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();
        //int min = (int) ((currHP * 1000f / maxHP));
        int min = (int) (1000 * ((double) currHP / (double) maxHP));
        mplew.writeShort(SendOpcode.FIELD_EFFECT.getValue());
        mplew.write(5);
        mplew.writeInt(oid);
        mplew.writeInt(min);
        mplew.writeInt(1000);
        mplew.write(tagColor);
        mplew.write(tagBgColor);
        return mplew.getPacket();
    }

    public static byte[] customShowBossHP(byte call, int oid, long currHP, long maxHP, byte tagColor, byte tagBgColor) {
        final MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();
        //int min = (int) ((currHP * 1000f / maxHP));
        int min = (int) (1000 * ((double) currHP / (double) maxHP));
        System.out.println(min);
        System.out.println(min * 1000);
        mplew.writeShort(SendOpcode.FIELD_EFFECT.getValue());
        mplew.write(call);
        mplew.writeInt(oid);
        mplew.writeInt(min);
        mplew.writeInt(1000);
        mplew.write(tagColor);
        mplew.write(tagBgColor);
        return mplew.getPacket();
    }

everything else is easy to convert

replacing this line in MapleLifeFactory file also unlock its int cap
stats.setHp(MapleDataTool.getLongConvert("maxHP", monsterInfoData));

then just go thru and update source to change HP very simple

if i built the system from ground up in less than 1 hour im sure dev can apply this to src. gms style wise this wont change anything. very useful system for custom servers

**Comment by brandy** [comment]
Why not make a pull request so they can merge it? :smile:

**Comment by ronancpl** [comment]
As of v83, no actual mobs have HP over 2b HP (would be the case for custom mobs, obviously). Closing issue.
