### ISSUE TITLE
proper player item vac

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#77]
List<MapleMapObject> items = player.getMap().getMapObjectsInRange(player.getPosition(), Double.POSITIVE_INFINITY, Arrays.asList(MapleMapObjectType.ITEM));
                for (MapleMapObject item : items) {
                    MapleMapItem mapItem = (MapleMapItem) item;
                    if (mapItem.getOwner() == player.getId() || mapItem.getOwner() == player.getPartyId()) {
                        player.pickupItem(mapItem);
                    }
                }
                break;

outside of party, its player owned item else its players party id.

**Comment by ronancpl** [comment]
Covered that now. What is the owner timeout for a dropped item?

**Comment by resinate** [comment]
dunno the system never uses it lol, if theres no owner on items it doesnt loot them

**Comment by ronancpl** [comment]
Already measured this, clients waits 15secs before claiming other's loot. Did the same for the itemvac.
