### ISSUE TITLE
Error - Shop Potions

### ISSUE THREAD

**Issue by NovaStory** [ronancpl/MapleSolaxiaV2#78]
I have found a mistake, That is when buying potions in stores, Too much DC.

**Comment by vcoc** [comment]
Dude, YOU NEED USE A CUSTOM WZ!!! Close this "f3".

**Comment by ronancpl** [comment]
Not to encourage the usage of v83 clean wz's, but it was stated on the 3rd SQL script (shop_update) that the use of that script code would generate dependency with the provided wz on both client and server side.
