### ISSUE TITLE
Mulung Dojo Spawns the wrong Monsters and they drop the wrong potions (white potion, blue potion, mana elixir)

### ISSUE THREAD

**Issue by Alex-0000** [ronancpl/MapleSolaxiaV2#79]
these potions go inside your inventory instead of being consumed.

Also the monsters drop regular items, like master chronos is dropping cog.

**Comment by ronancpl** [comment]
Should I assume you tried "forcevac" to get those dojo pots on your inventory? That's bound to happen. Regarding regular items, did you load the 2nd script? That should have been solved there.
