### ISSUE TITLE
character stuck?

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#85]
Ok sir. Some players play then they get character stuck and i try !dc bame not work how can i fix and also which v83 localhost is best to use can u please give me link?

**Comment by ronancpl** [comment]
Some of the localhosts I use are there on the general tools link on readme, check those. Regarding player stuck, if that happens in such a way they can't re-login a check on the tables' data is needed, as the character's DB may have become corrupted somehow (things such as an item labeled with an petid with no entry on pet table).
