### ISSUE TITLE
error code  -2147467259

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#88]
error code  -2147467259
how can i fix?

many people gets error code  -2147467259
windows defender off
firewall off

**Comment by freshmany** [comment]
error code 2147467259 unspecified error

**Comment by ronancpl** [comment]
These dc's are happening maybe because someone is not using the provided WZ's, instead their own. Some bosses, for instance, got their HPBar on my WZ's, reportedly giving out dc's and consequent "character stuck" for those who doesn't have the HPbar data in their WZ's.

**Comment by resinate** [comment]
ronan u have custom HP packet in the source why not use that to create them in game instead of wz modding?

**Comment by ronancpl** [comment]
Do you know how customShowBossHP works? I dunno, and as I can see it, they won't activate a HP bar on a boss if the client doesn't have the proper boss bar data to display it. Images are not sent via packet, just routine calls to the client to display those things.
