### ISSUE TITLE
NPC Dialogue showing random 'n' characters

### ISSUE THREAD

**Issue by brandy** [ronancpl/MapleSolaxiaV2#89]
Most NPC chats show something like this. It seems to be that the `n`'s are dependent on how many options there are.

![n on npc](https://image.prntscr.com/image/f4G8-DFcT3uago-VoFguCQ.png)

**Comment by ronancpl** [comment]
This issue is localhost-related. Some localhosts gives this problem, some don't, I suppose that's handled regarding on the character encoding being used on them. Sadly, MapleSilver's (those present on the Drive) will show this issue.

**Comment by brandy** [comment]
Ahh gotcha. I'll play around with the localhost and see if I can find a way to fix it
