### ISSUE TITLE
Server Crash - RollBack... ?

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#90]
Hello ronan -
when i leave the server online.
then players, lag and server crash -
and players lost all there items in equipment?

how can i fix that sir?

that the only main bug that i need to fix....
please help

Maybe its the client i guess////

**Comment by ronancpl** [comment]
Player lagging on changing maps and whatnot is something I've not experienced when debugging alone, although that has been reported a lot by people playing with client WZs different than those I provided. I'm not sure if there is indeed something in the server code that is causing these laggings. As I said before, no actions can be taken if the source of these problems are not identified.
Regarding rollbacks, if the server crashed when people was playing the game, as the current code is nothing can be done to recover the last state the player was, the DB saves only at dc'ing, changing channel, jobs and other cases.

**Comment by freshmany** [comment]
server crashing, people lose items -
cant log back in to server

can you give me a link to your full wz?
thanks

if i use that everything is fine right?

**Comment by ronancpl** [comment]
Take a read on the readme, there should be the link you need.

Yes, this server is designed to run using the provided WZ, use that and it should be fine. These ppl unable to log back into the server may have encountered a scenario where their WZs does not have certain data the server is demanding them to run, generating exceptions and client crashes.

**Comment by freshmany** [comment]
thanks alot ronancpl =]
i will try find your wz then....

so agian
i do !saveall in channel 1 and 2
then i !shutdown or !shutdownnow

put the server back up - ?
=======================
and do i use the rev101 _ wz?
or currect wz? there two files in google drive

**Comment by freshmany** [comment]
ty vcoc

**Comment by freshmany** [comment]
every time i restart the server do i have to delete the files in logs?
each day when i restart?
files logs - then it shows
 2017-09-07
2017-09-08
2017-09-09

?
then it say error storage gachapon usedcommand
show its all ?

**Comment by ronancpl** [comment]
Lof files does no effect to the server, you delete or use it's info as you want...
