### ISSUE TITLE
Auto Save feature

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#91]
this will minimize amount of rollbacks in server crashes or deadlocks

add this under server.java

add this at end of:
@Override
public void run() {

        TimerManager.getInstance().register(new save(), 600000);
        System.out.println("Solaxia Auto Save is now online.");

Add this down the file

    public class save implements Runnable {

        @Override
        public void run() {
            for (World world : Server.getInstance().getWorlds()) {
                for (MapleCharacter chr : world.getPlayerStorage().getAllCharacters()) {
                    chr.saveToDB();
                    chr.yellowMessage("Your progress has been auto saved.");
                }
            }
        }
    }

**Comment by freshmany** [comment]
hello, resinate can you please help me to located server.java - i cannot find it and please tell me step where i add auto save

**Comment by freshmany** [comment]
@override
public void run() {
    TimerManager.getInstance().register(new save(), 600000);
    System.out.println("Solaxia Auto Save is now online.");

public class save implements Runnable {

    @Override
    public void run() {
        for (World world : Server.getInstance().getWorlds()) {
            for (MapleCharacter chr : world.getPlayerStorage().getAllCharacters()) {
                chr.saveToDB();
                chr.yellowMessage("Your progress has been auto saved.");
            }
        }
    }
}

i just add like that in netbean?

**Comment by freshmany** [comment]
hi resinate
please tell me where do i add them-
i try to follow it but it didnt work for me all error on netbean

**Comment by tienvtran89** [comment]
try this : 
add  tMan.register(new save(), 600000);  
under => tMan.start();

then add below => public void shutdown() {
`public class save implements Runnable {

    @Override
    public void run() {
        for (World world : Server.getInstance().getWorlds()) {
            for (MapleCharacter chr : world.getPlayerStorage().getAllCharacters()) {
                chr.saveToDB();
                chr.yellowMessage("Your progress has been auto saved.");
            }
        }
    }
}`

**Comment by freshmany** [comment]
so when i do !shutdownnow
it just auto save yes ?
and no rollback or inventory wipe?

**Comment by ronancpl** [comment]
Implemented autosave.
