### ISSUE TITLE
Server Problems...

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#92]
hello when i you your current wz files
and i login server -

Kerning city map 
all the npc is out of place
and no pqs is working?
when me and few friends try to party with 4 people for kpq
doesnt warp us in, keep saying make sure your party are level requirment
i set kpq 21-200?

**Comment by ronancpl** [comment]
Hi. I can assure you all npcs on Kerning are actually on their right place, as of v83 meant them to be. Regarding KPQ, as it is, you have to get all players on the same map, on the same channel, and everyone level 21 to 30 to work. Testing this here, with 3 ppl on given conditions, started the PQ just fine.
