### ISSUE TITLE
Inventory Equip Tab Wipe

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#94]
Only main thing is inventory equip tab wipe...

When players get stuck - they cant use website to unstuck themself
and when i try to !dc playername that doesnt work also
and if i just do !saveall !shutdownnow

and restart the server. They log back in - people that are stuck - all there equipment tab in inventory got wipe.

Honestly is there any way to fix that? i really want to fix that.
Can someone help me please

**Comment by ronancpl** [comment]
You should debug what is going on the DB of your server. Out of the blue there is no simple answer, as some concurrency problem may have made your character data corrupted.

Check for some of the stuck players, if they are throwing NullPointExceptions when the player is trying to log in find and edit the snippet on the source that is causing this exception thrown, and take some decisions about what to do with possible corrupted data (as of discard incomplete data or w/e).

Finally, check if with the changes they can login again.

**Comment by freshmany** [comment]
is it possible to make a command that dc stuck character?
right now the one in your source !dc name
it doesnt work for stuck character?

possible to give me the command to add in ? 
to dc stuck characters?
