### ISSUE TITLE
Server issue + Client issue

### ISSUE THREAD

**Issue by talex9** [ronancpl/MapleSolaxiaV2#97]
Greetings!

this is my first time installing maplesolaxia and -though i followed the tutorial- i've encountered two issues. hopefully this is the proper place to make my consultation.

first, after using launch.bat, a number of errors occur in succession. they include exceptions with null pointers and missing resources of pinkbeanbattle, zakumbattle, trains, just to name a few. is this supposed to happen or have i made a mistake / am missing something? nevertheless, after some time it states 'Solaxia is now online.', and then, i proceed to execute 'Localhostv83.exe', which leads me to the next issue,

second, a 'java.security.InvalidKeyException: Illegal key size or default parameters' error appears after attempting to connect the client. afterwards, it closes. this happens without managing a login screen of any sorts.

i have a gratitude for any solutions offered for these inquires or for directing me into the proper steps to follow.

**Comment by brandy** [comment]
>java.security.InvalidKeyException

You need to do this:

```
Overwrite whenever prompted with the JAR files under "jce_policy-7/UnlimitedJCEPolicy" in these Java folders:
C:\Program Files\Java\jre7\lib
C:\Program Files\Java\jre7\lib\ext
C:\Program Files\Java\jre7\lib\security
C:\Program Files\Java\jdk1.7.0_01\lib
C:\Program Files\Java\jdk1.7.0_01\jre\lib
C:\Program Files\Java\jdk1.7.0_01\jre\lib\ext
C:\Program Files\Java\jdk1.7.0_01\jre\lib\security
```

**Comment by ronancpl** [comment]
When loading the server the cmd should be clean, only log-type prints appearing on the display. Anything else means you have not set the system up properly. Make sure you're using Java 7 as well.

**Comment by talex9** [comment]
Hi!

yes, i had both done (though a 'clean cmd' happens if i run the executable by double click, right? or should i do something in particular?). 

i also happened to install java jre-8u144 before and i'm thinking that might be causing both issues. in case it's that, is there any way you know i can have both?

**Comment by ronancpl** [comment]
Double-clicking/executing the launch.bat file is the only way I know to have it loading properly. On the idea, yes it is possible to have both java7 and java8 on your machine, just switching on the environment variables the order of the java's on the pathlist when you want to use one or another. In action, no I have no clue on how to maintain two java's of different versions on a machine.

**Comment by talex9** [comment]
news of progression!

it turns out the issue was the usage of the java8 instead of the java7. i followed on to change the environment variable on system in control panel so path pointed to jre7. afterwards, i renamed the jre on the jdk folder and made a copy of the jre7 and set it to take the place of the jre.

ran the server, ran the client, failed, then ran wamp because i had forgotten, started all services, ran the server again just in case, ran the client again and now i'm in!

gratitude on all advices.
