### ISSUE TITLE
Crash on 3rd job

### ISSUE THREAD

**Issue by brandy** [ronancpl/MapleSolaxiaV2#99]
I'm trying to do my 3rd job adv, however, I'm having some issues and not sure what's causing it or how exactly to fix it.

I talk to the demon door and get teleported into a map. I go to the right to enter the portal to enter the map where you kill your job instructor but it crashes my game.

I checked the console and this is what it says (pretty sure the exception is for this issue)
![console](https://image.prntscr.com/image/pvHtsmsRRMiRGow4T6bt5A.png)

**Comment by ronancpl** [comment]
It got an exception on the client-side. I can be wrong, but most commonly that happens when one is not using the provided WZ on the client-side as well as the wz.xml at server-side. Is that your case?

**Comment by brandy** [comment]
Lemme double check and get back to you
